//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueLocation
    {
        public CliqueLocation()
        {
            this.CliqueRequests = new HashSet<CliqueRequest>();
            this.CliqueWeathers = new HashSet<CliqueWeather>();
            this.CliqueLocationTweets = new HashSet<CliqueLocationTweet>();
            this.CliqueEvents = new HashSet<CliqueEvent>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual ICollection<CliqueRequest> CliqueRequests { get; set; }
        public virtual ICollection<CliqueWeather> CliqueWeathers { get; set; }
        public virtual ICollection<CliqueLocationTweet> CliqueLocationTweets { get; set; }
        public virtual ICollection<CliqueEvent> CliqueEvents { get; set; }
    }
}
