//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueWeather
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> MinTemp { get; set; }
        public Nullable<int> MaxTemp { get; set; }
        public Nullable<int> Wind { get; set; }
        public Nullable<int> Humidity { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Score { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
    
        public virtual CliqueLocation CliqueLocation { get; set; }
    }
}
