//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueWeather
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public string MinTemp { get; set; }
        public string MaxTemp { get; set; }
        public string WindSpeed { get; set; }
        public string Humidity { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string Temp { get; set; }
        public string WeatherDay { get; set; }
        public string WindDirection { get; set; }
        public string Weather { get; set; }
    
        public virtual CliqueClaimRequest CliqueClaimRequest { get; set; }
    }
}
