//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueTweet
    {
        public CliqueTweet()
        {
            this.CliqueUserTweets = new HashSet<CliqueUserTweet>();
            this.CliqueLocationTweets = new HashSet<CliqueLocationTweet>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string PostedBy { get; set; }
        public string PostedAt { get; set; }
        public Nullable<double> Score { get; set; }
        public System.DateTime AddedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string ProfileImageURL { get; set; }
        public string TweetIdStr { get; set; }
    
        public virtual ICollection<CliqueUserTweet> CliqueUserTweets { get; set; }
        public virtual ICollection<CliqueLocationTweet> CliqueLocationTweets { get; set; }
    }
}
