//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueRequest
    {
        public CliqueRequest()
        {
            this.CliqueLocationTweets = new HashSet<CliqueLocationTweet>();
            this.CliqueUserTweets = new HashSet<CliqueUserTweet>();
            this.CliqueLocationEvents = new HashSet<CliqueLocationEvent>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string BuildingName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual CliqueLocation CliqueLocation { get; set; }
        public virtual ICollection<CliqueLocationTweet> CliqueLocationTweets { get; set; }
        public virtual ICollection<CliqueUserTweet> CliqueUserTweets { get; set; }
        public virtual CliqueUser CliqueUser { get; set; }
        public virtual ICollection<CliqueLocationEvent> CliqueLocationEvents { get; set; }
    }
}
