//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAmenityMapping
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public int AmenityId { get; set; }
    
        public virtual HomeAwayProperty HomeAwayProperty { get; set; }
    }
}
