//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterMessage
    {
        public int Id { get; set; }
        public decimal MessageId { get; set; }
        public string MessageIdString { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> TwitterUserId { get; set; }
        public Nullable<int> TwitterKeywordId { get; set; }
    
        public virtual TwitterKeyword TwitterKeyword { get; set; }
        public virtual TwitterUser TwitterUser { get; set; }
    }
}
