//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfilerCommon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ipl_userprofilerEntities : DbContext
    {
        public ipl_userprofilerEntities()
            : base("name=ipl_userprofilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CliqueLocation> CliqueLocations { get; set; }
        public virtual DbSet<CliqueRequest> CliqueRequests { get; set; }
        public virtual DbSet<CliqueWeather> CliqueWeathers { get; set; }
        public virtual DbSet<CliqueTweet> CliqueTweets { get; set; }
        public virtual DbSet<CliqueLocationTweet> CliqueLocationTweets { get; set; }
        public virtual DbSet<CliqueUserTweet> CliqueUserTweets { get; set; }
        public virtual DbSet<CliqueEvent> CliqueEvents { get; set; }
        public virtual DbSet<CliqueUser> CliqueUsers { get; set; }
        public virtual DbSet<CliqueLocationEvent> CliqueLocationEvents { get; set; }
        public virtual DbSet<Amenitiy> Amenitiys { get; set; }
        public virtual DbSet<CliqueClaimRequest> CliqueClaimRequests { get; set; }
        public virtual DbSet<CliqueClaimRequestFeedback> CliqueClaimRequestFeedbacks { get; set; }
        public virtual DbSet<HomeAwayFeedback> HomeAwayFeedbacks { get; set; }
        public virtual DbSet<HomeAwayProperty> HomeAwayProperties { get; set; }
        public virtual DbSet<PropertyAmenityMapping> PropertyAmenityMappings { get; set; }
    }
}
